/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Advertisement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'content' : IDL.Text,
  'pointsReward' : IDL.Nat,
});
export const RewardStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserId = IDL.Principal;
export const RewardType = IDL.Variant({
  'cash' : IDL.Null,
  'giftCard' : IDL.Null,
});
export const RewardRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RewardStatus,
  'userId' : UserId,
  'rewardType' : RewardType,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveRewardRequest' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAd' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'deleteAd' : IDL.Func([IDL.Text], [], []),
  'getActiveAds' : IDL.Func([], [IDL.Vec(Advertisement)], ['query']),
  'getAllAds' : IDL.Func([], [IDL.Vec(Advertisement)], ['query']),
  'getAllRewardRequests' : IDL.Func([], [IDL.Vec(RewardRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingRewardRequests' : IDL.Func(
      [],
      [IDL.Vec(RewardRequest)],
      ['query'],
    ),
  'getPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalUsers' : IDL.Nat,
          'totalPoints' : IDL.Nat,
          'totalRewardRequests' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRewards' : IDL.Func([], [IDL.Vec(RewardRequest)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemReward' : IDL.Func([RewardType, IDL.Nat], [IDL.Text], []),
  'rejectRewardRequest' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAd' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'watchAd' : IDL.Func([IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Advertisement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'content' : IDL.Text,
    'pointsReward' : IDL.Nat,
  });
  const RewardStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const RewardType = IDL.Variant({ 'cash' : IDL.Null, 'giftCard' : IDL.Null });
  const RewardRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RewardStatus,
    'userId' : UserId,
    'rewardType' : RewardType,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'points' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveRewardRequest' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAd' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'deleteAd' : IDL.Func([IDL.Text], [], []),
    'getActiveAds' : IDL.Func([], [IDL.Vec(Advertisement)], ['query']),
    'getAllAds' : IDL.Func([], [IDL.Vec(Advertisement)], ['query']),
    'getAllRewardRequests' : IDL.Func([], [IDL.Vec(RewardRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingRewardRequests' : IDL.Func(
        [],
        [IDL.Vec(RewardRequest)],
        ['query'],
      ),
    'getPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalUsers' : IDL.Nat,
            'totalPoints' : IDL.Nat,
            'totalRewardRequests' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRewards' : IDL.Func([], [IDL.Vec(RewardRequest)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemReward' : IDL.Func([RewardType, IDL.Nat], [IDL.Text], []),
    'rejectRewardRequest' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAd' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'watchAd' : IDL.Func([IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };