/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Advertisement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'content' : IDL.Text,
  'pointsReward' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'upiId' : IDL.Opt(IDL.Text),
  'points' : IDL.Nat,
});
export const RewardType = IDL.Variant({
  'cash' : IDL.Null,
  'giftCard' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveRewardRequest' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAd' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'deleteAd' : IDL.Func([IDL.Text], [], []),
  'getActiveAds' : IDL.Func([], [IDL.Vec(Advertisement)], ['query']),
  'getCallerUpiId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserUpiId' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemReward' : IDL.Func([RewardType, IDL.Nat], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCallerUpiId' : IDL.Func([IDL.Text], [], []),
  'updateAd' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'watchAd' : IDL.Func([IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Advertisement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'content' : IDL.Text,
    'pointsReward' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'upiId' : IDL.Opt(IDL.Text),
    'points' : IDL.Nat,
  });
  const RewardType = IDL.Variant({ 'cash' : IDL.Null, 'giftCard' : IDL.Null });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveRewardRequest' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAd' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'deleteAd' : IDL.Func([IDL.Text], [], []),
    'getActiveAds' : IDL.Func([], [IDL.Vec(Advertisement)], ['query']),
    'getCallerUpiId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserUpiId' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemReward' : IDL.Func([RewardType, IDL.Nat], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCallerUpiId' : IDL.Func([IDL.Text], [], []),
    'updateAd' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'watchAd' : IDL.Func([IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };