/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Advertisement {
  'id' : string,
  'title' : string,
  'active' : boolean,
  'content' : string,
  'pointsReward' : bigint,
}
export type RewardType = { 'cash' : null } |
  { 'giftCard' : null };
export interface UserProfile {
  'name' : string,
  'upiId' : [] | [string],
  'points' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveRewardRequest' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAd' : ActorMethod<[string, string, bigint], string>,
  'deleteAd' : ActorMethod<[string], undefined>,
  'getActiveAds' : ActorMethod<[], Array<Advertisement>>,
  'getCallerUpiId' : ActorMethod<[], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserUpiId' : ActorMethod<[Principal], [] | [string]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'redeemReward' : ActorMethod<[RewardType, bigint], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCallerUpiId' : ActorMethod<[string], undefined>,
  'updateAd' : ActorMethod<
    [string, string, string, bigint, boolean],
    undefined
  >,
  'watchAd' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];